# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-07 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('nombre_med', models.CharField(max_length=50, null=True)),
                ('numero_lote', models.CharField(max_length=20, null=True)),
                ('fecha_elavorado', models.DateField(null=True)),
                ('fecha_vencimiento', models.DateField(null=True)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('precio', models.IntegerField(null=True)),
                ('tiempo_registro_medicamentos', models.DateTimeField(auto_now_add=True)),
                ('actualizado_medicamentos', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_paci', models.CharField(max_length=50, null=True)),
                ('apellido_paci', models.CharField(max_length=50, null=True)),
                ('cod_movil', models.IntegerField()),
                ('movil', models.IntegerField()),
                ('cod_tlf', models.IntegerField()),
                ('tlf', models.IntegerField()),
                ('direccion_paci', models.TextField(max_length=255, null=True)),
                ('fech_naci', models.DateField(null=True)),
                ('tiempo_registro_paciente', models.DateTimeField(auto_now_add=True)),
                ('actualizado_paciente', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(null=True)),
                ('nombre_serv', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('extencion_tlf', models.IntegerField(null=True)),
                ('asistente_serv', models.CharField(max_length=50, null=True)),
                ('tiempo_registro_servicios', models.DateTimeField(auto_now_add=True)),
                ('actualizado_servicios', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
