# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-07 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamentos',
            old_name='codigo',
            new_name='codigo_med',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='codigo',
            new_name='codigo_serv',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='tipo',
            new_name='tipo2',
        ),
    ]
